include: package:lint/strict.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    
  exclude: 
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - 'lib/generated'
    - 'lib/l10n'
    - 'lib/firebase_options.dart'

linter:
  rules:
    always_use_package_imports: false